### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by flutterderp** [flutterderp/Beep-boop#1]
- [x] Change level three headings in sidebar to level two
- [x] Change the sidebar `section` to an `aside` and change the current `aside`s in the sidebar to `div`s
- [x] Make blues a bit darker in header and link elements

**Comment by flutterderp** [comment]
Closed by 465a15296d317dfccb76aeb76c51802f192cfa33 and b6557296cb10d463fb542cdc3600930e083d6bb6.
